apiVersion: apps/v1
kind: Deployment

metadata:
  name: student-portal

spec:
  replicas: 5

  selector:
    matchLabels:
      app: student-portal

  template:
    metadata:
      labels:
        app: student-portal

    spec:
      containers:
      - name: student-portal
        image: student-portal:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
