apiVersion: v1
kind: Service

metadata:
  name: student-portal-service

spec:
  selector:
    app: student-portal

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

  type: NodePort
